import type {
  AlertItem,
  District,
  FieldReport,
  ForecastPoint,
  Infrastructure,
  Road,
  RiskZone,
} from "./types"

// Region focus: North Eastern Region of India (Sikkim / Darjeeling hills belt)
export const REGION_CENTER: [number, number] = [27.15, 88.6]

export const districts: District[] = [
  {
    id: "mangan",
    name: "Mangan",
    state: "North Sikkim",
    center: [27.51, 88.53],
    riskLevel: "severe",
    riskScore: 91,
    population: 43354,
    trend: "up",
    rainfall24h: 214,
    soilMoisture: 96,
    slope: 38,
  },
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    center: [27.33, 88.61],
    riskLevel: "high",
    riskScore: 78,
    population: 100286,
    trend: "up",
    rainfall24h: 168,
    soilMoisture: 88,
    slope: 29,
  },
  {
    id: "kalimpong",
    name: "Kalimpong",
    state: "West Bengal",
    center: [27.06, 88.47],
    riskLevel: "high",
    riskScore: 72,
    population: 251642,
    trend: "flat",
    rainfall24h: 141,
    soilMoisture: 81,
    slope: 26,
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    center: [27.04, 88.26],
    riskLevel: "moderate",
    riskScore: 58,
    population: 132016,
    trend: "down",
    rainfall24h: 96,
    soilMoisture: 69,
    slope: 24,
  },
  {
    id: "namchi",
    name: "Namchi",
    state: "South Sikkim",
    center: [27.16, 88.36],
    riskLevel: "moderate",
    riskScore: 49,
    population: 63557,
    trend: "flat",
    rainfall24h: 74,
    soilMoisture: 63,
    slope: 21,
  },
  {
    id: "gyalshing",
    name: "Gyalshing",
    state: "West Sikkim",
    center: [27.28, 88.26],
    riskLevel: "low",
    riskScore: 31,
    population: 36943,
    trend: "down",
    rainfall24h: 42,
    soilMoisture: 51,
    slope: 19,
  },
]

export const riskZones: RiskZone[] = [
  { id: "z1", districtId: "mangan", center: [27.51, 88.53], radius: 4200, riskLevel: "severe", riskScore: 91 },
  { id: "z2", districtId: "mangan", center: [27.44, 88.56], radius: 3200, riskLevel: "severe", riskScore: 86 },
  { id: "z3", districtId: "gangtok", center: [27.33, 88.61], radius: 3600, riskLevel: "high", riskScore: 78 },
  { id: "z4", districtId: "gangtok", center: [27.29, 88.58], radius: 2600, riskLevel: "high", riskScore: 74 },
  { id: "z5", districtId: "kalimpong", center: [27.06, 88.47], radius: 3400, riskLevel: "high", riskScore: 72 },
  { id: "z6", districtId: "kalimpong", center: [27.1, 88.53], radius: 2400, riskLevel: "moderate", riskScore: 61 },
  { id: "z7", districtId: "darjeeling", center: [27.04, 88.26], radius: 3000, riskLevel: "moderate", riskScore: 58 },
  { id: "z8", districtId: "namchi", center: [27.16, 88.36], radius: 2800, riskLevel: "moderate", riskScore: 49 },
  { id: "z9", districtId: "gyalshing", center: [27.28, 88.26], radius: 2600, riskLevel: "low", riskScore: 31 },
]

export const roads: Road[] = [
  {
    id: "nh10",
    name: "NH-10 (Sevoke – Gangtok)",
    status: "blocked",
    note: "Debris flow near Rangpo, cleared ETA 8h",
    path: [
      [27.04, 88.26],
      [27.09, 88.4],
      [27.17, 88.5],
      [27.33, 88.61],
    ],
  },
  {
    id: "ns-highway",
    name: "North Sikkim Highway",
    status: "blocked",
    note: "Road washed out beyond Chungthang",
    path: [
      [27.33, 88.61],
      [27.44, 88.56],
      [27.51, 88.53],
    ],
  },
  {
    id: "kalimpong-link",
    name: "Kalimpong – Algarah Link",
    status: "restricted",
    note: "Single-lane, slow-moving slump",
    path: [
      [27.06, 88.47],
      [27.1, 88.53],
      [27.13, 88.6],
    ],
  },
  {
    id: "namchi-road",
    name: "Namchi – Jorethang Rd",
    status: "open",
    note: "Clear, routine monitoring",
    path: [
      [27.16, 88.36],
      [27.1, 88.32],
      [27.04, 88.26],
    ],
  },
  {
    id: "geyzing-road",
    name: "Gyalshing – Pelling Rd",
    status: "open",
    note: "Clear",
    path: [
      [27.28, 88.26],
      [27.3, 88.22],
    ],
  },
]

export const infrastructure: Infrastructure[] = [
  { id: "v1", name: "Chungthang", type: "village", position: [27.6, 88.64], riskLevel: "severe", people: 4200 },
  { id: "v2", name: "Dzongu", type: "village", position: [27.48, 88.5], riskLevel: "severe", people: 7100 },
  { id: "h1", name: "Mangan District Hospital", type: "hospital", position: [27.51, 88.53], riskLevel: "high" },
  { id: "s1", name: "Govt. School Singhik", type: "school", position: [27.46, 88.55], riskLevel: "high", people: 320 },
  { id: "b1", name: "Sanklang Bridge", type: "bridge", position: [27.42, 88.55], riskLevel: "severe" },
  { id: "sh1", name: "Gangtok Relief Shelter", type: "shelter", position: [27.33, 88.61], riskLevel: "moderate", people: 800 },
  { id: "v3", name: "Algarah", type: "village", position: [27.12, 88.58], riskLevel: "moderate", people: 3600 },
  { id: "b2", name: "Teesta Bridge", type: "bridge", position: [27.09, 88.42], riskLevel: "high" },
  { id: "sh2", name: "Namchi Community Hall", type: "shelter", position: [27.16, 88.36], riskLevel: "low", people: 500 },
]

export const forecast: ForecastPoint[] = [
  { label: "Now", rainfall: 32, risk: 84 },
  { label: "+6h", rainfall: 41, risk: 88 },
  { label: "+12h", rainfall: 46, risk: 92 },
  { label: "+18h", rainfall: 28, risk: 79 },
  { label: "+24h", rainfall: 18, risk: 66 },
  { label: "+36h", rainfall: 9, risk: 51 },
  { label: "+48h", rainfall: 4, risk: 38 },
]

export const alerts: AlertItem[] = [
  {
    id: "a1",
    title: "Red Alert — Imminent Landslide Risk",
    district: "Mangan, North Sikkim",
    level: "severe",
    time: "2026-09-03T08:15:00+05:30",
    message:
      "IMD red rainfall warning + soil saturation at 96%. Model predicts high probability of slope failure within 12h along NH-North Sikkim corridor. Evacuate Chungthang and Dzongu low-lying settlements.",
    channels: ["sms", "app", "siren"],
    audiences: ["District Admin", "SDRF", "Local Community"],
    acknowledged: false,
  },
  {
    id: "a2",
    title: "Orange Alert — Elevated Risk",
    district: "Gangtok, Sikkim",
    level: "high",
    time: "2026-09-03T07:40:00+05:30",
    message:
      "Continuous rainfall for 18h. Cracks reported near Ranipool. Restrict non-essential travel on NH-10 and pre-position response teams.",
    channels: ["sms", "app"],
    audiences: ["District Admin", "Police", "Local Community"],
    acknowledged: false,
  },
  {
    id: "a3",
    title: "Road Closure — NH-10",
    district: "Kalimpong, West Bengal",
    level: "high",
    time: "2026-09-03T06:05:00+05:30",
    message: "Debris flow near Rangpo has blocked NH-10. Traffic diverted via Algarah link road. Clearance underway.",
    channels: ["app", "sms"],
    audiences: ["District Admin", "Transport Dept", "Local Community"],
    acknowledged: true,
  },
  {
    id: "a4",
    title: "Yellow Alert — Watch",
    district: "Darjeeling, West Bengal",
    level: "moderate",
    time: "2026-09-02T22:20:00+05:30",
    message: "Moderate rainfall expected overnight. Monitor slope sensors and report any new cracks or seepage.",
    channels: ["app"],
    audiences: ["Field Officials"],
    acknowledged: true,
  },
]

export const initialReports: FieldReport[] = [
  {
    id: "r1",
    category: "crack",
    description: "Fresh tension crack ~15m long across the hill road, widening since morning.",
    location: [27.35, 88.6],
    place: "Ranipool, Gangtok",
    reporter: "Field Officer T. Lepcha",
    time: "2026-09-03T08:02:00+05:30",
    severity: "high",
    status: "synced",
    photo: "/reports/crack-road.png",
  },
  {
    id: "r2",
    category: "blocked-road",
    description: "Debris and boulders fully blocking the carriageway near the culvert.",
    location: [27.09, 88.42],
    place: "Rangpo, NH-10",
    reporter: "PWD Patrol",
    time: "2026-09-03T06:18:00+05:30",
    severity: "severe",
    status: "synced",
    photo: "/reports/blocked-road.png",
  },
  {
    id: "r3",
    category: "slope-movement",
    description: "Slow slump visible above the tea garden, retaining wall bulging.",
    location: [27.06, 88.47],
    place: "Algarah, Kalimpong",
    reporter: "Volunteer R. Subba",
    time: "2026-09-02T19:45:00+05:30",
    severity: "moderate",
    status: "queued",
    photo: "/reports/slope-movement.png",
  },
]

export const dataSources = [
  { id: "imd", name: "IMD Rainfall API", status: "live", detail: "Updated 4 min ago" },
  { id: "soil", name: "Soil Moisture Sensors", status: "live", detail: "126 / 132 online" },
  { id: "sat", name: "Satellite Imagery (INSAT)", status: "live", detail: "Last pass 22 min ago" },
  { id: "terrain", name: "Terrain / Slope (DEM)", status: "cached", detail: "Static layer" },
  { id: "history", name: "Historical Landslide Records", status: "live", detail: "1,204 events indexed" },
] as const
